# CI Pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: --no-git-tag-version version prerelease --preid=$(Build.BuildNumber)
    workingDir: 'Source/MSBuildTools.Unity/Packages/MSBuildForUnity'
  displayName: 'Update UPM Version'
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'Source/MSBuildTools.Unity/Packages/MSBuildForUnity'
    publishRegistry: 'useFeed'
    publishFeed: '0cb95e25-9194-4ccd-9afb-439b25ecb93a/a3d1c3cc-6042-4e05-b699-39a947e75639'